### ISSUE TITLE
Custom Parameters

### ISSUE THREAD

**Issue by jeromegervais** [stoddabr/react-tableau-embed-live#21]
Hi,

Thanks for the lib.
I may miss something, is there a way to handle custom parameters ?

**Comment by stoddabr** [comment]
Hi @jeromegervais ,

Sorry but I'm not sure exactly what you mean by custom parameters? Is there a specific part of the documentation you are referencing?

If you're referring to [viz parameters](https://help.tableau.com/current/api/embedding_api/en-us/docs/embedding_api_parameters.html), you should be able to do it the same as filtering. See the example on filtering: https://github.com/stoddabr/react-tableau-embed-live/blob/main/example/react-tableau-embed-live-examples/src/tableau_examples/AddRemoveFilters.tsx

**Comment by jeromegervais** [comment]
Thanks @stoddabr 

Custom parameters are explained at the bottom of the page you pointed.

About the example you provided, I was trying to achieve something close to it, but during to initialization.
to equivalent (if I understand correctly) to 
`<tableau-viz><custom-parameter ... /<tableau-viz>`

**Comment by OhkaBaka** [comment]
> If you're referring to [viz parameters](https://help.tableau.com/current/api/embedding_api/en-us/docs/embedding_api_parameters.html), you should be able to do it the same as filtering. 

Do you mean using the [workbook].changeParameterValueAsync method (in lieu of applyFilterAsync)? That doesn't seem to work, I get a "Uncaught (in promise) TypeError: workbook.changeParameterValueAsync is not a function"

https://help.tableau.com/current/api/embedding_api/en-us/docs/embedding_api_parameters.html#change-parameters-interactively-after-initialization

(I'd be happy with just setting them on initialization, but I can't seem to find how to do that either)

**Comment by OhkaBaka** [comment]
(I'd be happy with just setting them on initialization, but I can't seem to find how to do that either)

**Comment by stoddabr** [comment]
Yeah that's exactly what I was thinking. Odd it's not working for you. 

What version of the API are you using? 

The ability to set parameters is pretty new (it wasn't a thing when I first built this library). I think that is the error you would see if you are using an older version of the tableau API or are querying from an older deployment of tableau server.

**Comment by manuschillernordlb** [comment]
I was wondering the same thing currently.
Documentation: https://help.tableau.com/current/api/embedding_api/en-us/docs/embedding_api_parameters.html#apply-custom-parameters-during-initialization-using-web-components

My goal: I want to open links within `TableauEmbed` in the iframe instead of a new tab.

What I tried:

```typescript
<TableauEmbed
    version="3.5.0"
    sourceUrl="###redacted###"
    toolbar="hidden"
    hide-tabs
    hide-edit-button
>
    <custom-parameter
        name=":linktarget"
        value="_top"
    />
</TableauEmbed>
```

**Comment by jo-ikor** [comment]
To add to @manuschillernordlb's comment:

The snippet mentioned above does work, but the typings are not correct, meaning the TS-compiler mentions an error that isn't one.

a potential fix would be adding a `children` type to `OptionalTableauVizProps` [here](https://github.com/stoddabr/react-tableau-embed-live/blob/c29de8b33104a13b5e96c0846f0723744e707958/src/lib/TableauEmbed/TableauViz.tsx#L61), either with a simple `children?: React.ReactNode`, or constrained to [`VizChildElements`](https://github.com/stoddabr/react-tableau-embed-live/blob/c29de8b33104a13b5e96c0846f0723744e707958/src/lib/TableauEmbed/ScrapedTableauTypes/VizInterfaces.ts#L80).

You'd probably also need to extend the intrisic elements a little more https://github.com/stoddabr/react-tableau-embed-live/blob/c29de8b33104a13b5e96c0846f0723744e707958/src/lib/TableauEmbed/TableauViz.tsx#L70
with something like `["custom-parameter"]: CustomParameter;`

**Comment by stoddabr** [comment]
Very cool. I like the approach a lot but might be more liberal with `any` in a final solution. My philosophy with this library is to keep things as loose as the underlying tableau library (and boy, do they play fast and loose).

@jo-ikor or @manuschillernordlb , would you kindly be willing to share working code (e.g. codepen) of the intrinsic parameters working (with `@ts-ignore`s peppered as needed)? I do not have/know of any tableau dashboards that use custom parameters at hand

**Comment by jo-ikor** [comment]
@stoddabr Sure :)

https://codesandbox.io/s/tableau-embed-w64vv2?file=/src/App.tsx

Basically, I'm testing this on a dashboard that has external links and I'm using the custom-parameter :linktarget to influence the way an external link behaves.

the v3 API supports custom-parameters as a way to reference the old, v2 embedding parameters, docs are here:  
https://help.tableau.com/current/api/embedding_api/en-us/docs/embedding_api_parameters.html#about-custom-parameters  
and a list of parameters, including the `:linktarget`, that we're using is here:  
https://help.tableau.com/current/pro/desktop/en-us/embed_list.htm#URL_params  

Please check both .d.ts files in the CSB, I can't get the TableauEmbed module augmentation to work, I thinks it's due to the naming (the component and the interface both share the same name...)

**Comment by stoddabr** [comment]
Fixed a minor type issue with your PR and merged it
